### ISSUE TITLE
Bitcoin  dissapeared

### ISSUE THREAD

**Issue by Bergssprangare** [startcoin-project/copay#3]
80 Bitcoins were never transfered  to my StartJOIN account. I;ve contacted you before with no response.

Regards

**Comment by monicabtc888** [comment]
I also have a missing/lost transaction. Where/who do we contact for wallet support??

**Comment by lukem512** [comment]
Hi @Bergssprangare, please could you contact [hello@startjoin.com](mailto:hello@startjoin.com) and re-state your query? I've spoken to them but we'll need more details to proceed.
