### ISSUE TITLE
Needs USD

### ISSUE THREAD

**Issue by Nickfost** [startcoin-project/copay#5]

**Comment by lukem512** [comment]
Hi Nick,

you can set your default currency to USD by logging into your wallet, clicking settings and changing the 'alternate currency' to US Dollar.

<img width="984" alt="screen shot 2016-03-27 at 11 48 49" src="https://cloud.githubusercontent.com/assets/2834976/14065054/e8062e64-f411-11e5-9a1b-2b965681bf76.png">
